all:
  setup_library_type: '2'
  itunes_xml_location: '/Users/user/Music/iTunes/iTunes Music Library.xml'
  wf:
    watched_folders:
      - /Users/user/Music
      - /Users/users/Shared_Music
  aft:
    allowed_file_types:
      - mp3
  msp:
    media_scan_plan:
      - 'scan-media --type=filesystem'
      - 'scan-art --source=meta'
  results_per_page: 20
  allow_ffmpeg_transcoding: true
  ffmpeg_executable: /opt/local/var/macports/software/ffmpeg/0.6.1_0/opt/local/bin/ffmpeg
  music_proxy_port: 8096
  send_cookies_with_request: true
  sf_guard_plugin:
    remember_key_expiration_age: 25920000
  indexer:
    use_indexer: false
    settings:
      class: StreemeIndexerMysql
      auto-start: true
  setup_acl:
    allowed_ips:
      - 192.168.43.249
      - 123.0.0.1
